name: flutter_code_sample
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  intl: any
  sizer: ^2.0.15
  fluttertoast: ^8.2.1
  need_resume: ^1.0.7+1
  connectivity_plus: ^3.0.4
  flutter_bloc: ^7.3.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.1
  logger: ^1.3.0
  universal_html: ^2.2.1
  cached_network_image: ^3.2.3
  easy_debounce: 2.0.1
  animations: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  json_serializable: ^6.6.1
  retrofit_generator:  ^6.0.0+1
  build_runner: ^2.3.3
  freezed: ^2.3.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf

    # FaNum fonts
    - family: YekanBakhFaNumHairline
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_01_Hairline.ttf
    - family: YekanBakhFaNumThin
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_02_Thin.ttf
    - family: YekanBakhFaNumLight
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_03_Light.ttf
    - family: YekanBakhFaNumRegular
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_04_Regular.ttf
    - family: YekanBakhFaNumMedium
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_05_Medium.ttf
    - family: YekanBakhFaNumBold
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_06_Bold.ttf
    - family: YekanBakhFaNumHeavy
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_07_Heavy.ttf
    - family: YekanBakhFaNumFat
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_08_Fat.ttf

    # Roboto fonts
    - family: RobotoItalic
      fonts:
        - asset: fonts/Roboto_Italic.ttf
    - family: RobotoThin
      fonts:
        - asset: fonts/Roboto_02_Thin.ttf
    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto_03_Light.ttf
    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto_04_Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: fonts/Roboto_05_Medium.ttf
    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto_06_Bold.ttf
    - family: RobotoBlack
      fonts:
        - asset: fonts/Roboto_07_Black.ttf




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
