// ignore_for_file: constant_identifier_names
import 'package:flutter/widgets.dart';

/// Autogenerated class from [https://www.fluttericon.com/] which uses AppIcons.ttf from assets
class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData play = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData protein = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchased_diet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retry = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retry_curved_edge = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scale = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scale_report = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scale_with_foot = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_card_add = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sport = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tips = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walking_shoes = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrist = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baked_food = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carbo = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_rounded = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_tight_angle = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheese_toast = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_shorter_bottom_rounded = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cooking = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diet = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_calendar = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_pyramid = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mag = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData measure = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData author = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
